title: Noah Tonnesen
email: noah.tonnesen@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my personal website. I'm a full-stack developer with four years of experience in web development and database management applications.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ntonnes.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: NoahTonnesen
github_username: ntonnes

header_pages:
  - home.md
  - about.md
  - projects.md
  - blog.md
  - contact.md
  - resume.md

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap